services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: baselinker_php
    volumes:
      - .:/var/www/Baselinker
    environment:
      - BASELINKER_TOKEN=${BASELINKER_TOKEN}

  nginx:
    image: nginx:alpine
    container_name: baselinker_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/Baselinker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  redis:
    image: redis:alpine
    container_name: baselinker_redis